/**
 * AUTO-GENERATED by scripts/fetch-card-benefits.mjs
 * Last run: 2026-07-05
 *
 * Benefits are scraped from official issuer pages and parsed automatically.
 * Conditions (spend thresholds, caps, activation requirements) are folded
 * into descriptions where detected on the source page.
 *
 * Card benefits change frequently. Always verify current terms directly
 * with your card issuer before making financial decisions.
 *
 * Rewards Radar / Red Evolve Technologies Pvt. Ltd. is not affiliated
 * with any bank, card network, telecom operator, or insurer.
 */

export const DATA_DISCLAIMER =
  'Benefit information is scraped from official issuer pages and parsed automatically. Terms change frequently — always verify with your card issuer before relying on this data. Last database update: 2026-07-05.';

export type ResetPeriod = 'month' | 'quarter' | 'year' | 'once' | 'per-recharge';
export type BenefitCategory =
  | 'lounge'
  | 'insurance'
  | 'cashback'
  | 'ott'
  | 'discount'
  | 'health'
  | 'golf'
  | 'fuel'
  | 'dining'
  | 'travel'
  | 'other';
export type ProductType =
  | 'credit-card'
  | 'debit-card'
  | 'upi'
  | 'telecom'
  | 'health-insurance'
  | 'motor-insurance'
  | 'term-insurance';

export interface Benefit {
  id: string;
  title: string;
  category: BenefitCategory;
  description: string;
  value: string;
  quota: number | null;
  resetPeriod: ResetPeriod;
  howToClaim: string;
  accentColor: string;
  verified?: boolean;
  source?: string;
  lastVerified?: string;
  conditions?: string;
}

export interface RewardLogic {
  categories: string[];
  rewardRate: string;
  rewardType: 'cashback' | 'points' | 'miles' | 'voucher';
  pointValue?: string;
  onlineBonusRate?: string;
  offlineBonusRate?: string;
  fuelRate?: string;
  diningRate?: string;
  travelRate?: string;
  groceryRate?: string;
}

export interface Product {
  id: string;
  type: ProductType;
  issuer: string;
  name: string;
  network?: 'Visa' | 'Mastercard' | 'Rupay' | 'Amex' | 'Diners';
  annualFee?: number;
  joiningFee?: number;
  annualValueEstimate: number;
  benefits: Benefit[];
  rewardLogic?: RewardLogic;
}

export const products: Product[] = [

  // ─── HDFC REGALIA ───────────────────────────────────────────
  {
    id: 'hdfc-regalia',
    type: 'credit-card',
    issuer: 'HDFC Bank',
    name: 'HDFC Regalia Credit Card',
    network: 'Visa',
    annualFee: 2500,
    annualValueEstimate: 9200,
    benefits: [
      {
        id: 'hdfc-regalia-lounge-dom',
        title: 'Domestic Airport Lounge Access',
        category: 'lounge',
        description: '2 complimentary domestic airport lounge visits per quarter (8/year). IMPORTANT: Requires minimum spend of ₹1,00,000 in the preceding calendar quarter to qualify. Zero visits credited if spend threshold not met.',
        value: '2 visits/quarter',
        quota: 2,
        resetPeriod: 'quarter',
        howToClaim: 'Swipe your HDFC Regalia card at the lounge entrance. Check eligible lounges on HDFC SmartBuy or Visa lounge locator. Track eligibility via HDFC Netbanking.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia',
        lastVerified: '2025-01-15',
        conditions: 'Minimum spend of ₹1,00,000 in preceding calendar quarter required. Check eligibility on HDFC Netbanking before visiting lounge.',
      },
      {
        id: 'hdfc-regalia-lounge-intl',
        title: 'International Lounge via Priority Pass',
        category: 'lounge',
        description: '6 complimentary international lounge visits per year via Priority Pass (combined for primary + add-on cardholder). Priority Pass membership must be activated separately after completing 4 retail transactions.',
        value: '6 visits/year',
        quota: 6,
        resetPeriod: 'year',
        howToClaim: 'Complete 4 retail transactions first, then apply for Priority Pass via HDFC SmartBuy portal. Show Priority Pass card at international lounges. Note: Priority Pass used inside India will be charged to your card.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia',
        lastVerified: '2025-01-15',
        conditions: 'Complete minimum 4 retail transactions before applying for Priority Pass. 6 visits shared between primary and add-on cardholder. Usage inside India is chargeable.',
      },
      {
        id: 'hdfc-regalia-air-accident',
        title: 'Air Accident Insurance Cover',
        category: 'insurance',
        description: 'Personal accident death cover of ₹1 crore in case of air accidental death. Card must have been used at least once in preceding 60 days for cover to be active.',
        value: '₹1 crore cover',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Nominee contacts HDFC ERGO within 130 days of incident. Submit FIR, death certificate, boarding pass, and medical reports. Card must have been active (recent transaction) before incident.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia',
        lastVerified: '2025-01-15',
        conditions: 'Card must be active with at least one transaction in preceding 60 days. Claim must be raised within 130 days of incident.',
      },
      {
        id: 'hdfc-regalia-rewards',
        title: '4 Reward Points per ₹150 Spent',
        category: 'cashback',
        description: 'Earn 4 reward points on every ₹150 of retail spend. Bonus 10,000 points on ₹5L annual spend, additional 5,000 points on ₹8L annual spend. 1 point ≈ ₹0.50 when redeemed on SmartBuy for flights/hotels.',
        value: '4 pts/₹150',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Points credited automatically. Redeem via HDFC SmartBuy, NetBanking, or partner merchants. Points expire after 2 years.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia',
        lastVerified: '2025-01-15',
        conditions: 'Excludes fuel, wallet loads, and EMI transactions. Points expire in 2 years.',
      },
      {
        id: 'hdfc-regalia-fuel',
        title: 'Fuel Surcharge Waiver',
        category: 'fuel',
        description: '1% fuel surcharge waiver at all fuel stations across India on transactions between ₹400 and ₹5,000.',
        value: '1% waiver',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Pay fuel bill using HDFC Regalia card. Waiver applied automatically at POS terminal.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia',
        lastVerified: '2025-01-15',
        conditions: 'Valid on transactions between ₹400 and ₹5,000 only.',
      },
    ],
  },

  // ─── HDFC REGALIA GOLD ──────────────────────────────────────
  {
    id: 'hdfc-regalia-gold',
    type: 'credit-card',
    issuer: 'HDFC Bank',
    name: 'HDFC Regalia Gold Credit Card',
    network: 'Visa',
    annualFee: 2500,
    annualValueEstimate: 11000,
    benefits: [
      {
        id: 'hdfc-regalia-gold-lounge-dom',
        title: 'Domestic Airport Lounge Access',
        category: 'lounge',
        description: '3 complimentary domestic airport lounge visits per quarter (12/year). Requires minimum spend of ₹60,000 in the preceding calendar quarter. Zero visits if spend threshold not met.',
        value: '3 visits/quarter',
        quota: 3,
        resetPeriod: 'quarter',
        howToClaim: 'Show HDFC Regalia Gold card at eligible lounge. Check lounge list on HDFC portal. Track eligibility via Netbanking.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Minimum ₹60,000 spend in preceding calendar quarter required to unlock quarterly lounge benefit.',
      },
      {
        id: 'hdfc-regalia-gold-swiggy-one',
        title: 'Complimentary Swiggy One Membership',
        category: 'discount',
        description: 'Complimentary Swiggy One membership as welcome benefit. Includes free deliveries and exclusive restaurant discounts.',
        value: '~₹1,299/yr value',
        quota: 1,
        resetPeriod: 'year',
        howToClaim: 'Activate via Swiggy app using your registered mobile number linked to the card. Available as welcome benefit on card activation.',
        accentColor: '#E2593A',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Welcome benefit — activate within stated validity period after card issuance.',
      },
      {
        id: 'hdfc-regalia-gold-mmt-black',
        title: 'Complimentary MMT Black Gold Membership',
        category: 'travel',
        description: 'Complimentary MakeMyTrip Black Gold membership as welcome benefit. Includes exclusive hotel and flight discounts.',
        value: '~₹2,999/yr value',
        quota: 1,
        resetPeriod: 'year',
        howToClaim: 'Activate via MakeMyTrip app using the registered mobile number on your card account.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Welcome benefit — activate within stated validity period after card issuance.',
      },
      {
        id: 'hdfc-regalia-gold-air-accident',
        title: 'Air Accident Insurance Cover',
        category: 'insurance',
        description: 'Personal accident death cover of ₹1 crore in case of air accidental death.',
        value: '₹1 crore cover',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Nominee contacts HDFC ERGO within 130 days. Submit FIR, death certificate, boarding pass. Card must have been active before incident.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Card must be active with recent transaction before incident.',
      },
      {
        id: 'hdfc-regalia-gold-rewards',
        title: '4 Reward Points per ₹150 Spent',
        category: 'cashback',
        description: 'Earn 4 reward points on every ₹150 retail spend. 5X points on select brands via SmartBuy. Quarterly milestone: ₹1,500 voucher on ₹1.5L quarterly spend.',
        value: '4 pts/₹150',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Points auto-credited. Redeem via HDFC SmartBuy or NetBanking.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Excludes fuel, wallet loads, EMI. 5X on select SmartBuy merchants only.',
      },
    ],
  },

  // ─── HDFC DINERS BLACK ──────────────────────────────────────
  {
    id: 'hdfc-diners-black',
    type: 'credit-card',
    issuer: 'HDFC Bank',
    name: 'HDFC Diners Black Credit Card',
    network: 'Diners',
    annualFee: 10000,
    annualValueEstimate: 28000,
    benefits: [
      {
        id: 'hdfc-diners-black-lounge',
        title: 'Unlimited Airport Lounge Access',
        category: 'lounge',
        description: 'Unlimited complimentary domestic and international lounge access for primary cardholder. No quarterly or annual cap.',
        value: 'Unlimited',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Show HDFC Diners Black card at lounge entrance. Covers 1000+ lounges worldwide via Diners Club network.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/diners-black-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Primary cardholder only for unlimited access. Add-on cardholder benefits may differ.',
      },
      {
        id: 'hdfc-diners-black-rewards',
        title: '5 Reward Points per ₹150 on Dining & Travel',
        category: 'cashback',
        description: 'Earn 5 reward points per ₹150 on dining, travel, and entertainment. 2 points per ₹150 on all other spends. Annual fee waived on ₹5L annual spend.',
        value: '5 pts/₹150 (dining/travel)',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Points auto-credited each statement cycle. Redeem via HDFC SmartBuy, AirMiles, or partner merchants.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/diners-black-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Annual fee waived if annual spend exceeds ₹5,00,000.',
      },
      {
        id: 'hdfc-diners-black-golf',
        title: 'Complimentary Golf Games',
        category: 'golf',
        description: 'Complimentary golf games at select golf courses across India and internationally.',
        value: '~₹3,000/game value',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Book via HDFC Diners concierge. Check eligible courses on HDFC portal.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/diners-black-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Subject to course availability. Advance booking required via concierge.',
      },
      {
        id: 'hdfc-diners-black-air-accident',
        title: 'Air Accident Insurance Cover',
        category: 'insurance',
        description: 'Personal accident death cover of ₹2 crore in case of air accidental death.',
        value: '₹2 crore cover',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Nominee contacts HDFC ERGO. Submit required documentation within 130 days.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/diners-black-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Card must be active with recent transaction before incident.',
      },
    ],
  },

  // ─── HDFC MILLENNIA ─────────────────────────────────────────
  {
    id: 'hdfc-millennia',
    type: 'credit-card',
    issuer: 'HDFC Bank',
    name: 'HDFC Millennia Credit Card',
    network: 'Mastercard',
    annualFee: 1000,
    annualValueEstimate: 5800,
    benefits: [
      {
        id: 'hdfc-millennia-cashback-online',
        title: '5% Cashback on Top Shopping Apps',
        category: 'cashback',
        description: '5% cashback on Amazon, Flipkart, Myntra, Swiggy, Zomato, BookMyShow, Cult.fit, and other partner apps. Capped at ₹1,000 cashback per statement cycle across all partners combined.',
        value: '5% back (cap ₹1,000/mo)',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Pay via HDFC Millennia card on partner apps. Cashback credited as CashPoints within 90 days of statement generation. Redeem via NetBanking.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/millennia-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Capped at ₹1,000 CashPoints per statement cycle. Excludes EMI transactions.',
      },
      {
        id: 'hdfc-millennia-cashback-others',
        title: '1% Cashback on All Other Spends',
        category: 'cashback',
        description: '1% cashback on all spends not covered by the 5% partner category.',
        value: '1% back',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Applied automatically. Credited as CashPoints.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/millennia-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Excludes fuel, wallet loads, and EMI transactions.',
      },
      {
        id: 'hdfc-millennia-lounge',
        title: 'Domestic Airport Lounge Access',
        category: 'lounge',
        description: '1 complimentary domestic airport lounge visit per quarter.',
        value: '1 visit/quarter',
        quota: 1,
        resetPeriod: 'quarter',
        howToClaim: 'Show HDFC Millennia card at eligible lounges. Check lounge list on HDFC portal.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/millennia-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Check minimum spend requirement on HDFC portal — may require quarterly spend threshold.',
      },
      {
        id: 'hdfc-millennia-fuel',
        title: 'Fuel Surcharge Waiver',
        category: 'fuel',
        description: '1% fuel surcharge waiver at all fuel stations on transactions between ₹400 and ₹5,000.',
        value: '1% waiver',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Pay at fuel station using card. Waiver applied automatically.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/millennia-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Valid on transactions between ₹400 and ₹5,000 only.',
      },
    ],
  },

  // ─── SBI CARD ELITE ─────────────────────────────────────────
  {
    id: 'sbi-elite',
    type: 'credit-card',
    issuer: 'SBI Card',
    name: 'SBI Card ELITE',
    network: 'Mastercard',
    annualFee: 4999,
    annualValueEstimate: 13500,
    benefits: [
      {
        id: 'sbi-elite-lounge-dom',
        title: 'Domestic Airport Lounge Access',
        category: 'lounge',
        description: '2 complimentary domestic airport lounge visits per quarter (8 per year) via Visa/Mastercard lounge program. Not unlimited — quota is strictly 2 per quarter.',
        value: '2 visits/quarter',
        quota: 2,
        resetPeriod: 'quarter',
        howToClaim: 'Show SBI Card ELITE at lounge counter. Check eligible lounges via Mastercard lounge locator. No pre-booking required.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.sbicard.com/en/personal/credit-cards/travel/sbi-card-elite.page',
        lastVerified: '2025-01-15',
        conditions: '2 visits per quarter only — resets each calendar quarter. NOT unlimited.',
      },
      {
        id: 'sbi-elite-lounge-intl',
        title: 'International Lounge via Priority Pass',
        category: 'lounge',
        description: '6 complimentary international lounge visits per year via Priority Pass. Priority Pass membership must be activated through SBI Card portal before first use.',
        value: '6 visits/year',
        quota: 6,
        resetPeriod: 'year',
        howToClaim: 'Activate Priority Pass on SBI Card portal. Show Priority Pass card at international lounges. Visits beyond 6 per year will be charged.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.sbicard.com/en/personal/credit-cards/travel/sbi-card-elite.page',
        lastVerified: '2025-01-15',
        conditions: 'Must activate Priority Pass on SBI Card portal before use. Only 6 complimentary visits per year — additional visits charged.',
      },
      {
        id: 'sbi-elite-movie',
        title: '2 Free Movie Tickets per Month',
        category: 'discount',
        description: 'Buy 1 Get 1 free movie tickets on BookMyShow, up to 2 free tickets per month. Maximum discount ₹500 per ticket.',
        value: '2 tickets/month',
        quota: 2,
        resetPeriod: 'month',
        howToClaim: 'Pay on BookMyShow using SBI Card ELITE. BOGO offer applied automatically. Check BookMyShow offer section for eligible movies and screens.',
        accentColor: '#E2593A',
        verified: true,
        source: 'https://www.sbicard.com/en/personal/credit-cards/travel/sbi-card-elite.page',
        lastVerified: '2025-01-15',
        conditions: 'Maximum ₹500 discount per ticket. Limited to 2 free tickets per calendar month. Subject to BookMyShow availability.',
      },
      {
        id: 'sbi-elite-rewards',
        title: '5X Reward Points on Dining, Grocery & Departmental',
        category: 'cashback',
        description: 'Earn 5X reward points on dining, grocery, and departmental store spends. 2X on all other retail spends. 1 reward point = ₹0.25.',
        value: '5X pts (dining/grocery)',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Points auto-credited. Redeem via SBI Card portal or partner merchants.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.sbicard.com/en/personal/credit-cards/travel/sbi-card-elite.page',
        lastVerified: '2025-01-15',
        conditions: '1 reward point = ₹0.25. Points expire after 2 years.',
      },
      {
        id: 'sbi-elite-air-accident',
        title: 'Air Accident Insurance Cover',
        category: 'insurance',
        description: 'Personal accident death cover of ₹1 crore in case of air accidental death.',
        value: '₹1 crore cover',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Nominee raises claim with SBI Card insurance partner. Submit boarding pass, death certificate, and FIR within the claim window.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.sbicard.com/en/personal/credit-cards/travel/sbi-card-elite.page',
        lastVerified: '2025-01-15',
        conditions: 'Card must be active before incident. Verify exact activation conditions in card T&Cs.',
      },
    ],
  },

  // ─── SBI SIMPLYCLICK ─────────────────────────────────────────
  {
    id: 'sbi-simply-click',
    type: 'credit-card',
    issuer: 'SBI Card',
    name: 'SBI SimplyCLICK Credit Card',
    network: 'Visa',
    annualFee: 499,
    annualValueEstimate: 4200,
    benefits: [
      {
        id: 'sbi-simply-click-cb-online',
        title: '10X Reward Points on Partner Merchants',
        category: 'cashback',
        description: '10X reward points on Amazon, BookMyShow, Cleartrip, Lenskart, Netmeds, and other online partners. 5X on all other online spends. 1X on offline.',
        value: '10X pts on partners',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Shop via partner sites using SBI SimplyCLICK card. Points auto-credited.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.sbicard.com/en/personal/credit-cards/rewards/simplyclick-sbi-card.page',
        lastVerified: '2025-01-15',
        conditions: '1 reward point = ₹0.25. Annual e-voucher worth ₹2,000 on ₹1L annual spend.',
      },
      {
        id: 'sbi-simply-click-milestone',
        title: 'Annual e-Voucher on Milestone Spend',
        category: 'discount',
        description: 'Earn e-voucher worth ₹2,000 on achieving ₹1,00,000 annual spend. Additional ₹2,000 voucher on ₹2,00,000 annual spend.',
        value: '₹2,000–4,000 voucher',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Voucher credited automatically on crossing spend milestone. Check SBI Card portal for voucher details.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.sbicard.com/en/personal/credit-cards/rewards/simplyclick-sbi-card.page',
        lastVerified: '2025-01-15',
        conditions: 'Based on annual spend in card anniversary year, not calendar year.',
      },
    ],
  },

  // ─── BPCL SBI ───────────────────────────────────────────────
  {
    id: 'sbi-bpcl',
    type: 'credit-card',
    issuer: 'SBI Card',
    name: 'BPCL SBI Credit Card',
    network: 'Visa',
    annualFee: 499,
    annualValueEstimate: 6000,
    benefits: [
      {
        id: 'sbi-bpcl-fuel-rewards',
        title: '4.25% Value Back on BPCL Fuel',
        category: 'fuel',
        description: '13X reward points on BPCL fuel purchases (4.25% effective value back including 1% surcharge waiver). Also 5X reward points on grocery, dining, movies, and departmental stores.',
        value: '4.25% on BPCL fuel',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Pay at any BPCL petrol pump using this card. Points credited automatically. 1 reward point = ₹0.25.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.sbicard.com/en/personal/credit-cards/fuel/bpcl-sbi-card.page',
        lastVerified: '2025-01-15',
        conditions: 'Maximum 1,300 reward points per month on fuel spends. 1 reward point = ₹0.25.',
      },
      {
        id: 'sbi-bpcl-fuel-surcharge',
        title: 'Fuel Surcharge Waiver at BPCL',
        category: 'fuel',
        description: '1% fuel surcharge waiver on fuel transactions at BPCL pumps. Effectively increases total value back to 4.25%.',
        value: '1% surcharge waiver',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Automatic at BPCL pump. No separate activation needed.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.sbicard.com/en/personal/credit-cards/fuel/bpcl-sbi-card.page',
        lastVerified: '2025-01-15',
        conditions: 'Only at BPCL pumps. Other fuel stations not covered.',
      },
    ],
  },

  // ─── AXIS MAGNUS ────────────────────────────────────────────
  {
    id: 'axis-magnus',
    type: 'credit-card',
    issuer: 'Axis Bank',
    name: 'Axis Magnus Credit Card',
    network: 'Visa',
    annualFee: 12500,
    annualValueEstimate: 32000,
    benefits: [
      {
        id: 'axis-magnus-lounge',
        title: 'Unlimited Domestic + International Lounge Access',
        category: 'lounge',
        description: 'Unlimited complimentary lounge access at domestic and international airports for primary and add-on cardholders. No quarterly or annual cap.',
        value: 'Unlimited',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Show Axis Magnus card at lounge entrance. Covers 1000+ lounges globally.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.axisbank.com/retail/cards/credit-card/magnus-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Covers primary and add-on cardholder. No cap.',
      },
      {
        id: 'axis-magnus-miles-online',
        title: '12 EDGE Miles per ₹200 on Online Spends',
        category: 'cashback',
        description: 'Earn 12 EDGE Miles per ₹200 on online transactions. 6 EDGE Miles per ₹200 on offline transactions. 1 EDGE Mile = ₹1 when redeemed for flights/hotels via Axis Travel EDGE portal.',
        value: '12 miles/₹200 (online)',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Miles auto-credited. Redeem via Axis Travel EDGE portal or transfer to airline frequent flyer programs.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.axisbank.com/retail/cards/credit-card/magnus-credit-card',
        lastVerified: '2025-01-15',
        conditions: '1 EDGE Mile = ₹1 on Travel EDGE. Transfer ratio varies by airline partner.',
      },
      {
        id: 'axis-magnus-golf',
        title: '4 Complimentary Golf Games per Quarter',
        category: 'golf',
        description: '4 complimentary golf games or lessons per quarter at select golf courses across India.',
        value: '4 games/quarter',
        quota: 4,
        resetPeriod: 'quarter',
        howToClaim: 'Book via Axis Magnus concierge or directly at partner golf courses. Carry your Axis Magnus card for verification.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.axisbank.com/retail/cards/credit-card/magnus-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Subject to course availability. Advance booking required.',
      },
      {
        id: 'axis-magnus-travel-insurance',
        title: 'Comprehensive Travel Insurance',
        category: 'insurance',
        description: 'Travel insurance cover including trip cancellation, lost baggage, and emergency medical cover up to ₹50 lakh for international travel.',
        value: '₹50 lakh travel cover',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Contact Axis Magnus concierge to initiate claim. Keep all travel documents, bills, and boarding passes.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.axisbank.com/retail/cards/credit-card/magnus-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Verify exact cover terms in the card T&Cs. Travel must be booked using Axis Magnus card.',
      },
    ],
  },

  // ─── AXIS ACE ───────────────────────────────────────────────
  {
    id: 'axis-ace',
    type: 'credit-card',
    issuer: 'Axis Bank',
    name: 'Axis Ace Credit Card',
    network: 'Visa',
    annualFee: 499,
    annualValueEstimate: 4800,
    benefits: [
      {
        id: 'axis-ace-cb-swiggy-zomato',
        title: '5% Cashback on Swiggy, Zomato & Ola',
        category: 'cashback',
        description: '5% cashback on Swiggy, Zomato, and Ola transactions. No monthly cap on this category.',
        value: '5% back',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Pay via Axis Ace card on Swiggy, Zomato, or Ola apps. Cashback credited within 7 days of statement generation.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.axisbank.com/retail/cards/credit-card/ace-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'No cap on Swiggy/Zomato/Ola cashback. Annual fee waived on ₹2L spend.',
      },
      {
        id: 'axis-ace-cb-billpay',
        title: '4% Cashback on Bill Payments via Google Pay',
        category: 'cashback',
        description: '4% cashback on utility bill payments, mobile recharges, and DTH payments made via Google Pay using Axis Ace card.',
        value: '4% back',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Add Axis Ace card to Google Pay. Pay utility bills via GPay. Cashback auto-credited.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.axisbank.com/retail/cards/credit-card/ace-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Must pay via Google Pay specifically. Direct bank/biller payment not eligible.',
      },
      {
        id: 'axis-ace-cb-others',
        title: '2% Cashback on All Other Spends',
        category: 'cashback',
        description: '2% cashback on all other spends not in the 5% or 4% category. No upper cap.',
        value: '2% back (all others)',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Applied automatically on all eligible spends.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.axisbank.com/retail/cards/credit-card/ace-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Excludes fuel, wallet loads, and EMI transactions.',
      },
      {
        id: 'axis-ace-fuel',
        title: 'Fuel Surcharge Waiver',
        category: 'fuel',
        description: '1% fuel surcharge waiver at all fuel stations across India.',
        value: '1% waiver',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Pay at fuel station using Axis Ace card. Waiver applied automatically.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.axisbank.com/retail/cards/credit-card/ace-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Valid on transactions between ₹400 and ₹5,000.',
      },
    ],
  },

  // ─── AXIS FLIPKART ──────────────────────────────────────────
  {
    id: 'axis-flipkart',
    type: 'credit-card',
    issuer: 'Axis Bank',
    name: 'Axis Flipkart Credit Card',
    network: 'Visa',
    annualFee: 500,
    annualValueEstimate: 3600,
    benefits: [
      {
        id: 'axis-flipkart-cb-flipkart',
        title: '5% Cashback on Flipkart & Myntra',
        category: 'cashback',
        description: '5% unlimited cashback on all Flipkart and Myntra purchases.',
        value: '5% back',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Pay via Axis Flipkart card on Flipkart or Myntra. Cashback credited automatically.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.axisbank.com/retail/cards/credit-card/flipkart-axis-bank-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Annual fee waived on ₹2L annual spend.',
      },
      {
        id: 'axis-flipkart-cb-preferred',
        title: '4% Cashback on Preferred Partners',
        category: 'cashback',
        description: '4% cashback on Cleartrip, PVR Cinemas, Tata Play, and other preferred partners.',
        value: '4% back',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Pay via card on partner platforms. Cashback auto-credited.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.axisbank.com/retail/cards/credit-card/flipkart-axis-bank-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Partner list subject to change. Check Axis Bank portal for current partners.',
      },
      {
        id: 'axis-flipkart-cb-others',
        title: '1.5% Cashback on All Other Spends',
        category: 'cashback',
        description: '1.5% unlimited cashback on all other online and offline spends.',
        value: '1.5% back',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Applied automatically on all eligible spends.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.axisbank.com/retail/cards/credit-card/flipkart-axis-bank-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Excludes fuel, wallet loads, and EMI.',
      },
    ],
  },

  // ─── AMAZON PAY ICICI ───────────────────────────────────────
  {
    id: 'icici-amazon-pay',
    type: 'credit-card',
    issuer: 'ICICI Bank',
    name: 'Amazon Pay ICICI Credit Card',
    network: 'Visa',
    annualFee: 0,
    annualValueEstimate: 5200,
    benefits: [
      {
        id: 'icici-amazon-pay-cb-prime',
        title: '5% Cashback on Amazon (Prime Members)',
        category: 'cashback',
        description: '5% unlimited cashback on all Amazon.in purchases for Amazon Prime members. No monthly or annual cap.',
        value: '5% back (Prime)',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Pay via Amazon Pay ICICI card on Amazon.in. Cashback credited to Amazon Pay balance within 24 hours of delivery.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.icicibank.com/personal-banking/cards/credit-card/amazon-pay-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Requires active Amazon Prime membership. Non-Prime members get 3% cashback instead.',
      },
      {
        id: 'icici-amazon-pay-cb-non-prime',
        title: '3% Cashback on Amazon (Non-Prime Members)',
        category: 'cashback',
        description: '3% cashback on Amazon.in purchases for non-Prime members.',
        value: '3% back (non-Prime)',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Cashback credited to Amazon Pay balance automatically.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.icicibank.com/personal-banking/cards/credit-card/amazon-pay-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Upgrade to Prime for 5% rate. Both rates have no upper cap.',
      },
      {
        id: 'icici-amazon-pay-cb-partners',
        title: '2% Cashback on 200+ Partner Merchants',
        category: 'cashback',
        description: '2% cashback at 200+ Amazon Pay partner merchants including Cleartrip, BigBasket, 1mg, and more.',
        value: '2% back (partners)',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Pay via Amazon Pay ICICI at partner checkout. Cashback goes to Amazon Pay balance.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.icicibank.com/personal-banking/cards/credit-card/amazon-pay-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Partner list available on Amazon Pay portal. Check before assuming eligibility.',
      },
      {
        id: 'icici-amazon-pay-cb-others',
        title: '1% Cashback on All Other Spends',
        category: 'cashback',
        description: '1% cashback on all other spends not in the Amazon or partner categories.',
        value: '1% back',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Applied automatically. Credited to Amazon Pay balance.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.icicibank.com/personal-banking/cards/credit-card/amazon-pay-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Excludes fuel and EMI transactions.',
      },
    ],
  },

  // ─── ICICI CORAL ────────────────────────────────────────────
  {
    id: 'icici-coral',
    type: 'credit-card',
    issuer: 'ICICI Bank',
    name: 'ICICI Coral Credit Card',
    network: 'Visa',
    annualFee: 500,
    annualValueEstimate: 3200,
    benefits: [
      {
        id: 'icici-coral-movie',
        title: '2 Free Movie Tickets per Month',
        category: 'discount',
        description: 'Buy 1 Get 1 free on movie tickets via BookMyShow, up to 2 free tickets per month. Maximum discount ₹250 per ticket.',
        value: '2 tickets/month',
        quota: 2,
        resetPeriod: 'month',
        howToClaim: 'Pay on BookMyShow using ICICI Coral card. BOGO applied automatically. Check eligible movies in BookMyShow offer section.',
        accentColor: '#E2593A',
        verified: true,
        source: 'https://www.icicibank.com/personal-banking/cards/credit-card/coral-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Maximum ₹250 discount per ticket. 2 free tickets per calendar month.',
      },
      {
        id: 'icici-coral-lounge',
        title: 'Domestic Airport Lounge Access',
        category: 'lounge',
        description: '1 complimentary domestic airport lounge visit per quarter via Visa/Mastercard lounge program.',
        value: '1 visit/quarter',
        quota: 1,
        resetPeriod: 'quarter',
        howToClaim: 'Show ICICI Coral card at eligible lounges. Check lounge list on ICICI portal.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.icicibank.com/personal-banking/cards/credit-card/coral-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Verify current lounge access terms on ICICI portal — conditions may have changed.',
      },
      {
        id: 'icici-coral-fuel',
        title: 'Fuel Surcharge Waiver',
        category: 'fuel',
        description: '1% fuel surcharge waiver at all fuel stations.',
        value: '1% waiver',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Pay at fuel station using card. Waiver applied automatically.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.icicibank.com/personal-banking/cards/credit-card/coral-credit-card',
        lastVerified: '2025-01-15',
        conditions: 'Check minimum/maximum transaction limits on ICICI portal.',
      },
    ],
  },

  // ─── KOTAK ROYALE ───────────────────────────────────────────
  {
    id: 'kotak-royale',
    type: 'credit-card',
    issuer: 'Kotak Mahindra Bank',
    name: 'Kotak Royale Signature Credit Card',
    network: 'Visa',
    annualFee: 999,
    annualValueEstimate: 6400,
    benefits: [
      {
        id: 'kotak-royale-lounge',
        title: 'Domestic Airport Lounge Access',
        category: 'lounge',
        description: '2 complimentary domestic airport lounge visits per quarter (8 per year).',
        value: '2 visits/quarter',
        quota: 2,
        resetPeriod: 'quarter',
        howToClaim: 'Show Kotak Royale Signature card at eligible lounges. Check lounge list via Visa lounge locator.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.kotak.com/en/personal-banking/cards/credit-cards/royale-signature-credit-card.html',
        lastVerified: '2025-01-15',
        conditions: 'Verify current spend thresholds on Kotak portal — may require minimum quarterly spend.',
      },
      {
        id: 'kotak-royale-rewards',
        title: '4X Reward Points on Travel, Entertainment & Dining',
        category: 'cashback',
        description: 'Earn 4X reward points on travel, entertainment, and dining spends. 2X on grocery. 1X on all other spends.',
        value: '4X pts (travel/dining)',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Points auto-credited. Redeem via Kotak portal or partner merchants.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.kotak.com/en/personal-banking/cards/credit-cards/royale-signature-credit-card.html',
        lastVerified: '2025-01-15',
        conditions: 'Check point value and expiry on Kotak portal.',
      },
      {
        id: 'kotak-royale-air-accident',
        title: 'Air Accident Insurance Cover',
        category: 'insurance',
        description: 'Personal accident death cover of ₹50 lakh in case of air accidental death.',
        value: '₹50 lakh cover',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Nominee contacts Kotak card insurance desk. Submit boarding pass, death certificate, and supporting documents.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.kotak.com/en/personal-banking/cards/credit-cards/royale-signature-credit-card.html',
        lastVerified: '2025-01-15',
        conditions: 'Card must be active before incident. Verify exact terms in card T&Cs.',
      },
      {
        id: 'kotak-royale-fuel',
        title: 'Fuel Surcharge Waiver',
        category: 'fuel',
        description: '1% fuel surcharge waiver at all fuel stations across India.',
        value: '1% waiver',
        quota: null,
        resetPeriod: 'month',
        howToClaim: 'Pay at fuel station using card. Applied automatically.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'https://www.kotak.com/en/personal-banking/cards/credit-cards/royale-signature-credit-card.html',
        lastVerified: '2025-01-15',
        conditions: 'Check transaction limits on Kotak portal.',
      },
    ],
  },

  // ─── TELECOM ────────────────────────────────────────────────
  {
    id: 'jio-999',
    type: 'telecom',
    issuer: 'Jio',
    name: 'Jio ₹999 / 84 days Plan',
    annualValueEstimate: 2800,
    benefits: [
      {
        id: 'jio-999-hotstar',
        title: 'Free JioHotstar Subscription',
        category: 'ott',
        description: 'Complimentary JioHotstar Mobile plan bundled with recharge. Must be manually activated — does NOT auto-activate for all users.',
        value: '~₹149/month value',
        quota: null,
        resetPeriod: 'per-recharge',
        howToClaim: 'Open MyJio app → My Vouchers → Activate JioHotstar voucher. Must activate within plan validity.',
        accentColor: '#E2593A',
        verified: true,
        source: 'https://www.jio.com/en-in/4g-plans',
        lastVerified: '2025-01-15',
        conditions: 'Must activate manually in MyJio app within plan validity. Does not auto-activate.',
      },
      {
        id: 'jio-999-cloud',
        title: '50GB JioCloud Storage',
        category: 'other',
        description: 'Free 50GB cloud storage on JioCloud bundled with the plan.',
        value: '50GB cloud storage',
        quota: null,
        resetPeriod: 'per-recharge',
        howToClaim: 'Login to JioCloud app with your Jio number. Storage automatically available.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'https://www.jio.com/en-in/4g-plans',
        lastVerified: '2025-01-15',
        conditions: 'Linked to active Jio connection.',
      },
    ],
  },
  {
    id: 'airtel-999',
    type: 'telecom',
    issuer: 'Airtel',
    name: 'Airtel ₹999 / 84 days Plan',
    annualValueEstimate: 2400,
    benefits: [
      {
        id: 'airtel-999-ott',
        title: 'Apollo 24|7 Circle + OTT Trials',
        category: 'ott',
        description: 'Apollo 24|7 Circle membership and OTT trial subscriptions bundled. Must be manually redeemed via Airtel Thanks app under "Rewards" tab.',
        value: '~₹300 value',
        quota: null,
        resetPeriod: 'per-recharge',
        howToClaim: 'Open Airtel Thanks app → Rewards tab → Redeem bundled benefits within plan validity period.',
        accentColor: '#E2593A',
        verified: true,
        source: 'https://www.airtel.in/recharge-online',
        lastVerified: '2025-01-15',
        conditions: 'Must redeem manually in Airtel Thanks app. Benefits vary by plan variant and availability.',
      },
      {
        id: 'airtel-999-wynk',
        title: 'Wynk Music Premium',
        category: 'ott',
        description: 'Ad-free Wynk Music streaming bundled with the plan. Auto-linked to Airtel number.',
        value: '~₹49/month value',
        quota: null,
        resetPeriod: 'per-recharge',
        howToClaim: 'Login to Wynk Music app with your Airtel number. Premium features available automatically.',
        accentColor: '#E2593A',
        verified: true,
        source: 'https://www.airtel.in/recharge-online',
        lastVerified: '2025-01-15',
        conditions: 'Auto-linked. Works only on the registered Airtel number.',
      },
    ],
  },

  // ─── INSURANCE ──────────────────────────────────────────────
  {
    id: 'health-comprehensive',
    type: 'health-insurance',
    issuer: 'Generic (most insurers)',
    name: 'Comprehensive Health Insurance Policy',
    annualValueEstimate: 6500,
    benefits: [
      {
        id: 'health-comp-checkup',
        title: 'Free Annual Health Checkup',
        category: 'health',
        description: '1 free annual health checkup per insured adult member. Covers basic blood work, ECG, and general screening at network diagnostic centers. Resets every policy anniversary year — most policyholders never use this.',
        value: '~₹1,500–3,000 value',
        quota: 1,
        resetPeriod: 'year',
        howToClaim: 'Book via your insurer\'s app or portal at a network diagnostic center. Log in, go to "Wellness" or "Benefits" section. Some insurers require calling their health desk.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'Standard benefit in most IRDAI-regulated comprehensive health policies',
        lastVerified: '2025-01-15',
        conditions: 'Must be booked at network center. Check your specific policy document for included tests and eligible centers.',
      },
      {
        id: 'health-comp-teleconsult',
        title: 'Free Doctor Teleconsultations',
        category: 'health',
        description: 'Complimentary video/phone consultations with network doctors per year. Typically 4–12 consultations depending on insurer and plan.',
        value: '~₹500/consult',
        quota: 4,
        resetPeriod: 'year',
        howToClaim: 'Book via insurer\'s app (e.g. Practo, Apollo, or insurer-specific) using your policy number. Some insurers use third-party teleconsult platforms.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'Standard benefit in most IRDAI-regulated comprehensive health policies',
        lastVerified: '2025-01-15',
        conditions: 'Number of free consultations varies by policy (4–12). Check your policy document for exact count and eligible specialties.',
      },
      {
        id: 'health-comp-wellness',
        title: 'Wellness & Fitness Discounts',
        category: 'health',
        description: 'Discounts on gym memberships, fitness apps, and diet consultations for active policyholders maintaining healthy habits.',
        value: 'Up to 20% discount',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Enroll in insurer wellness program via their app. Complete health challenges or step count targets to unlock discounts.',
        accentColor: '#C89B3C',
        verified: true,
        source: 'Standard benefit in most IRDAI-regulated comprehensive health policies',
        lastVerified: '2025-01-15',
        conditions: 'Varies significantly by insurer. Check your specific policy for enrolled wellness partners and discount terms.',
      },
    ],
  },
  {
    id: 'motor-comprehensive',
    type: 'motor-insurance',
    issuer: 'Generic (most insurers)',
    name: 'Comprehensive Motor Insurance Policy',
    annualValueEstimate: 2500,
    benefits: [
      {
        id: 'motor-comp-roadside',
        title: 'Free Roadside Assistance',
        category: 'other',
        description: 'Bundled 24/7 roadside assistance for breakdowns, towing, flat tyre, battery jump start, and fuel delivery. Most policyholders never note the helpline number until they need it.',
        value: '~₹1,500/yr value',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'Call your insurer\'s roadside assistance number (printed on your policy document). Save this number in your phone now — you will need it at the worst time.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'Standard benefit in most comprehensive motor policies in India',
        lastVerified: '2025-01-15',
        conditions: 'Number of free calls may be limited (typically 3–5 per year). Check your policy document.',
      },
      {
        id: 'motor-comp-ncb',
        title: 'No Claim Bonus Protection Add-on',
        category: 'other',
        description: 'If you purchased the NCB protector add-on, your No Claim Bonus discount is preserved even after filing one claim. NCB can be up to 50% discount on Own Damage premium after 5 claim-free years.',
        value: 'Up to 50% premium saved',
        quota: null,
        resetPeriod: 'year',
        howToClaim: 'No action needed if add-on is purchased. NCB protected automatically when filing a covered claim. Declare NCB when renewing with a new insurer.',
        accentColor: '#2F7A6D',
        verified: true,
        source: 'IRDAI motor insurance guidelines',
        lastVerified: '2025-01-15',
        conditions: 'Only if NCB Protector add-on was explicitly purchased. Check your policy schedule document.',
      },
    ],
  },
];

export function getProductsByType(type: ProductType): Product[] {
  return products.filter((p) => p.type === type);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export type AmountRangeId =
  | 'under-500'
  | '500-2000'
  | '2000-10000'
  | '10000-50000'
  | '50000-plus';

export type DemoTab = 'cards' | 'telecom' | 'insurance';

export type RewardSuggestion = {
  rank: number;
  name: string;
  paymentType: 'Credit Card' | 'Debit Card' | 'UPI';
  rate: string;
  ratePercent: number;
  howTo: string;
  brandColor: string;
  network: string;
  estimatedReward: number;
};

export const ISSUER_COLORS: Record<string, string> = {
  'HDFC Bank': '#004C8F',
  'Axis Bank': '#971237',
  'SBI Card': '#22409A',
  'ICICI Bank': '#F58220',
  'Amazon': '#E47911',
  'Kotak Mahindra Bank': '#ED1C24',
  'YES Bank': '#004990',
  'RBL Bank': '#2E3192',
  'Standard Chartered': '#0072AA',
  'American Express': '#006FCF',
  'Citibank': '#003B70',
  'Google Pay': '#4285F4',
  'PhonePe': '#5F259F',
  'Paytm': '#00BAF2',
  'BHIM': '#097939',
  'NPCI': '#097939',
  'Jio': '#0A2885',
  'Airtel': '#E40000',
  'Vi': '#E60000',
  'BSNL': '#00529B',
  'Tata Digital': '#6B2D5C',
  'Insurance': '#2F7A6D',
};

export function getProductsForDemoTab(tab: DemoTab): Product[] {
  switch (tab) {
    case 'cards':
      return products.filter((p) => p.type === 'credit-card' || p.type === 'debit-card');
    case 'telecom':
      return products.filter((p) => p.type === 'telecom');
    case 'insurance':
      return products.filter(
        (p) =>
          p.type === 'health-insurance' ||
          p.type === 'motor-insurance' ||
          p.type === 'term-insurance',
      );
  }
}

const CATEGORY_LABELS: Record<BenefitCategory, string> = {
  lounge: '✈ LOUNGE',
  insurance: '🛡 COVER',
  cashback: '💰 CASHBACK',
  ott: '🎬 OTT',
  discount: '🏷 DISCOUNT',
  health: '🩺 HEALTH',
  golf: '⛳ GOLF',
  fuel: '⛽ FUEL',
  dining: '🍽 DINING',
  travel: '✈ TRAVEL',
  other: '📌 OTHER',
};

const RESET_SUBLABELS: Record<ResetPeriod, string> = {
  month: 'resets monthly',
  quarter: 'resets quarterly',
  year: 'resets yearly',
  once: 'one-time benefit',
  'per-recharge': 'per recharge cycle',
};

export function getProductMeta(p: Product): string {
  const fee =
    p.annualFee === 0
      ? 'lifetime free'
      : p.annualFee != null
        ? `₹${p.annualFee.toLocaleString('en-IN')} fee`
        : null;
  const parts = [p.issuer, `${p.benefits.length} benefit${p.benefits.length === 1 ? '' : 's'}`];
  if (fee) parts.splice(1, 0, fee);
  return parts.join(' · ');
}

export function benefitToDisplay(b: Benefit): {
  cat: string;
  title: string;
  sub: string;
  val: string;
  color: string;
} {
  let val: string;
  if (b.quota === null) {
    val = b.category === 'insurance' || b.value === '✓' ? '✓' : '∞';
  } else {
    val = `${b.quota}/${b.quota}`;
  }
  return {
    cat: CATEGORY_LABELS[b.category],
    title: b.title,
    sub: RESET_SUBLABELS[b.resetPeriod],
    val,
    color: b.accentColor,
  };
}

const AMOUNT_MIDPOINTS: Record<AmountRangeId, number> = {
  'under-500': 300,
  '500-2000': 1250,
  '2000-10000': 6000,
  '10000-50000': 30000,
  '50000-plus': 75000,
};

export function parseRatePercent(rate: string): number {
  const range = rate.match(/(\d+(?:\.\d+)?)\s*[–-]\s*(\d+(?:\.\d+)?)\s*%/);
  if (range) return (parseFloat(range[1]) + parseFloat(range[2])) / 2;

  const slashPct = rate.match(/\(~(\d+(?:\.\d+)?)%\)/);
  if (slashPct) return parseFloat(slashPct[1]);

  const pct = rate.match(/(\d+(?:\.\d+)?)\s*%/);
  if (pct) return parseFloat(pct[1]);

  const miles = rate.match(/(\d+(?:\.\d+)?)\s*(?:EDGE Miles|CV Points|RP|MR|points?)\s*\/\s*₹?\s*(\d+)/i);
  if (miles) {
    const num = parseFloat(miles[1]);
    const denom = parseFloat(miles[2]);
    return (num / denom) * 100;
  }

  const multiplier = rate.match(/(\d+(?:\.\d+)?)X/i);
  if (multiplier) return parseFloat(multiplier[1]) * 0.5;

  return 1;
}

function categoryLookupKey(txType: string, category: string): string {
  return `${txType}:${category}`;
}

function productMatchesTx(
  product: Product,
  txType: string,
  category: string,
): boolean {
  const rl = product.rewardLogic;
  if (!rl) return false;
  const key = categoryLookupKey(txType, category);
  const cats = rl.categories;
  if (cats.includes(key)) return true;
  if (cats.includes(txType)) return true;
  if (cats.includes(category)) return true;
  if (txType === 'fuel' && cats.includes('fuel')) return true;
  return cats.some(
    (c) =>
      c === `online:${category}` ||
      c === `offline:${category}` ||
      c === `dining:${category}` ||
      c === `travel:${category}` ||
      c === `pharmacy:${category}` ||
      c === `hospital:${category}` ||
      c.endsWith(`:${category}`),
  );
}

export function getEffectiveRewardRate(
  product: Product,
  txType: string,
  category?: string,
): { rate: string; percent: number } {
  const rl = product.rewardLogic;
  if (!rl) return { rate: '0%', percent: 0 };

  const key = category ? categoryLookupKey(txType, category) : txType;

  if (key.includes('amazon') && rl.onlineBonusRate) {
    const p = parseRatePercent(rl.onlineBonusRate);
    return { rate: rl.onlineBonusRate, percent: p };
  }
  if (key.includes('flipkart') && rl.onlineBonusRate) {
    return { rate: rl.onlineBonusRate, percent: parseRatePercent(rl.onlineBonusRate) };
  }
  if (
    (key.includes('swiggy') || key.includes('food-delivery') || category === 'food-delivery') &&
    rl.diningRate
  ) {
    return { rate: rl.diningRate, percent: parseRatePercent(rl.diningRate) };
  }
  if (txType === 'fuel' && rl.fuelRate) {
    return { rate: rl.fuelRate, percent: parseRatePercent(rl.fuelRate) };
  }
  if (txType === 'dining' && rl.diningRate) {
    return { rate: rl.diningRate, percent: parseRatePercent(rl.diningRate) };
  }
  if (txType === 'travel' && rl.travelRate) {
    return { rate: rl.travelRate, percent: parseRatePercent(rl.travelRate) };
  }
  if (category === 'grocery' && rl.groceryRate) {
    return { rate: rl.groceryRate, percent: parseRatePercent(rl.groceryRate) };
  }
  if (txType === 'online' && rl.onlineBonusRate) {
    return { rate: rl.onlineBonusRate, percent: parseRatePercent(rl.onlineBonusRate) };
  }
  if (txType === 'offline' && rl.offlineBonusRate) {
    return { rate: rl.offlineBonusRate, percent: parseRatePercent(rl.offlineBonusRate) };
  }

  return { rate: rl.rewardRate, percent: parseRatePercent(rl.rewardRate) };
}

export function getRewardProducts(audience: 'personal' | 'business'): Product[] {
  return products.filter((p) => {
    if (!p.rewardLogic) return false;
    const isBusiness = p.rewardLogic.categories.includes('business');
    if (audience === 'business') return isBusiness;
    return p.type === 'upi' || !isBusiness;
  });
}

function paymentTypeLabel(
  type: ProductType,
): 'Credit Card' | 'Debit Card' | 'UPI' {
  if (type === 'credit-card') return 'Credit Card';
  if (type === 'debit-card') return 'Debit Card';
  return 'UPI';
}

function defaultNetwork(product: Product): string {
  if (product.network) return product.network;
  if (product.type === 'upi') return 'Rupay';
  return 'Visa';
}

export function getRewardSuggestions(
  txType: string,
  category: string,
  amountRange: AmountRangeId,
  audience: 'personal' | 'business',
  limit = 3,
): RewardSuggestion[] {
  const midpoint = AMOUNT_MIDPOINTS[amountRange];
  const candidates = getRewardProducts(audience).filter((p) =>
    productMatchesTx(p, txType, category),
  );

  const scored = candidates
    .map((p) => {
      const { rate, percent } = getEffectiveRewardRate(p, txType, category);
      const topBenefit = p.benefits.find((b) => b.category === 'cashback') ?? p.benefits[0];
      return {
        name: p.name,
        paymentType: paymentTypeLabel(p.type),
        rate,
        ratePercent: percent,
        howTo: topBenefit?.howToClaim ?? `Use ${p.name} for this transaction.`,
        brandColor: ISSUER_COLORS[p.issuer] ?? '#6B7280',
        network: defaultNetwork(p),
        estimatedReward: Math.round((midpoint * percent) / 100),
      };
    })
    .sort((a, b) => b.ratePercent - a.ratePercent);

  return scored.slice(0, limit).map((entry, index) => ({
    ...entry,
    rank: index + 1,
  }));
}
